project_name: halp
release:
  github:
    owner: josh5276
    name: halp
  name_template: '{{.Tag}}'
brews:
  - name: halp
    commit_author:
      name: Josh Silvas
      email: josh.silvas@networktocode.com
    tap:
      owner: josh5276
      name: halp
    folder: Formula
    caveats: |
      Halp v{{ .Tag }} Notes:
        1. Halp will create it's own system keychain called 'Go Internal'
          1a. You may need to reauthenticate halp to this keychain after update because the binary is
              a different signature.
        2. Release changelog located at:
          - https://github.com/josh5276/halp/releases/tag/{{ .Tag }}
        3. For issues with this tool, please sumbit a GitHub issue here:
          - https://github.com/josh5276/halp/issues
    homepage: https://github.com/josh5276/halp
    description: |
      Halp is a cli helper to manage Tempo/Jira tooling and other things.
    skip_upload: auto
    test: system "#{bin}/halp"
    install: bin.install "halp"
nfpms:
  - id: halp
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - halp_nix
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Linux
    vendor: Josh Silvas
    homepage: https://github.com/josh5276/halp
    maintainer: Josh Silvas <josh.silvas@networktocode.com>
    description: |
        Halp is a cli helper to manage Tempo/Jira tooling and other things
    license: Apache 2.0
    formats:
      - deb
    bindir: /usr/local/bin
    epoch: 1
builds:
- goos:
  - darwin
  targets:
  - darwin_amd64
  main: cmd/main.go
  ldflags: -s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: halp
  env:
  - CGO_ENABLED=1
  lang: go
  id: halp_osx
- goos:
  - linux
  targets:
  - linux_amd64
  main: cmd/main.go
  ldflags: -s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -linkmode external -extldflags -static
  binary: halp
  env:
  - CC=x86_64-linux-musl-gcc
  - CXX=x86_64-linux-musl-g++
  - CGO_ENABLED=1
  lang: go
  id: halp_nix
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
    format: tar.gz
    files:
    - LICENSE*
    - README*
    - CHANGELOG*
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: build
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  api: https://github.com/api/v3/
  upload: https://github.com/api/uploads/
  download: https://github.com/
