# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Halp < Formula
  desc "Halp is a cli helper to manage Tempo/Jira tooling and other things.
"
  homepage "https://github.com/josh5276/halp"
  version "0.1.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/josh5276/halp/releases/download/0.1.1/halp_Darwin_x86_64.tar.gz"
    sha256 "548c963490144911b5cdc5dccc3db7b2c93342fe0a5a5b092ccbdcea62972ec0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/josh5276/halp/releases/download/0.1.1/halp_Linux_x86_64.tar.gz"
    sha256 "64d31d971c024d93dfbb9cc726c96fe4ac2c4f17449796d044ba1be5e4911575"
  end

  def install
    bin.install "halp"
  end

  def caveats; <<~EOS
    Halp v0.1.1 Notes:
      1. Halp will create it's own system keychain called 'Go Internal'
        1a. You may need to reauthenticate halp to this keychain after update because the binary is
            a different signature.
      2. Release changelog located at:
        - https://github.com/josh5276/halp/releases/tag/0.1.1
      3. For issues with this tool, please sumbit a GitHub issue here:
        - https://github.com/josh5276/halp/issues
  EOS
  end

  test do
    system "#{bin}/halp"
  end
end
